// // Given a string columnTitle that represents the column title as appears in an Excel sheet, return its corresponding column number.

// // For example:

// // ![image](image.png)

// // Example 1:

// // Input: columnTitle = "A"

// // Output: 1

// // Example 2:

// // Input: columnTitle = "AB"

// // Output: 28

// // Example 3:

// // Input: columnTitle = "ZY"

// // Output: 701

// // Constraints:

// // 1 <= columnTitle.length <= 7

// // columnTitle consists only of uppercase English letters.

// // // columnTitle is in the range ["A", "FXSHRXW"].

// //------------------------------------------------------------------------------

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"

// Output: "e"

// Explanation: 'e' is the letter that was added.

// Example 2:

// Input: s = "", t = "y"

// Output: "y"

// Constraints:

// 0 <= s.length <= 1000

// t.length == s.length + 1

// s and t consist of lowercase English letters.

// let fun = (letter1, letter2) => {
//   let ter1 = letter1.split("");
//   let ter2 = letter2.split("");
//   for (let i = 0; i < ter1.length; i++) {
//     for (let j = 0; j < ter2.length; j++) {
//       if (ter1[i] == ter2[j]) {

//         ter2[j] = null;
//       }
//     }

//   }

//   for (let i=0;i<ter2.length;i++) {
//     if ( ter2[i]!=null) {
//          return ter2[i]
//     }
//   }
// };
// console.log(fun("", "y"));

//-----------------------------------------------------
// Example 1:

// Input: ops = ["5","2","C","D","+"]

// Output: 30

// Explanation:
// "5" - Add 5 to the record, record is now [5].

// "2" - Add 2 to the record, record is now [5, 2].

// "C" - Invalidate and remove the previous score, record is now [5].

// "D" - Add 2 * 5 = 10 to the record, record is now [5, 10].

// "+" - Add 5 + 10 = 15 to the record, record is now [5, 10, 15].

// The total sum is 5 + 10 + 15 = 30.

// let fun = (arr) => {
//   for (let i = 0; i < arr.length; i++) {
//     if (arr[i] === "C") {
//       let a = arr.indexOf(arr[i]);
//       arr.splice(a - 1, 1);
//     }
//     if (arr[i] == "D") {
//       let prev = arr.indexOf(arr[i]);
//       console.log(arr[prev - 1]);
//       let multi = arr[prev - 1];
//     //   arr = multi * 2;
//     // ['5', 'C', 'D', '+']
//     }
//   }
//   return arr
// };
// console.log(fun(["5", "2", "C", "D", "+"]));

let fun = (arr) => {
  let arr1 = [];
  for (let i = 0; i < arr.length; i++) {
    switch (arr[i]) {
      case "0":
        arr1.push(0);
        break;
      case "1":
        arr1.push(1);
        break;
      case "2":
        arr1.push(2);
        break;
      case "3":
        arr1.push(3);
        break;
      case "4":
        arr1.push(4);
        break;
      case "5":
        arr1.push(5);
        break;
      case "6":
        arr1.push(6);
        break;
      case "7":
        arr1.push(7);
        break;
      case "8":
        arr1.push(8);
        break;
      case "9":
        arr1.push(9);
        break;
      case "C":
        {
          let a = arr.indexOf(arr[i]);
          arr1.splice(a - 1, 1);
        }

        break;
      case "D": {
        let b = arr.indexOf(arr[i]);

        if (arr1.length < 2) {
          arr1.push(2 * arr1[0]);
        } else {
          arr1.push(2 * arr1[b - 2]);
        }

        break;
      }
      case "+": {
       
        let a = arr1[0] + arr1[1];

        arr1.push(a);
        break;
      }
    }
  }
  return arr1.reduce((a, b) => {
    return a + b;
  }, 0);
};
console.log(fun(["5", "2", "C", "D", "+"]));
